import { Task, Employee } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  { id: 'tuannam', name: 'Tuấn Nam', email: 'tuannam@example.com', role: 'Thi công' },
  { id: 'chishuong', name: 'Chì Phương', email: 'chishuong@example.com', role: 'Thi công' },
  { id: 'thinhhien', name: 'Thịnh Hiền', email: 'thinhhien@example.com', role: 'Thi công' },
  { id: 'admin', name: 'Admin Manager', email: 'admin@workflow.com', role: 'Quản trị' },
];

export const INITIAL_TASKS: Task[] = [
  // THI CÔNG
  {
    id: 'tc1',
    title: 'Dán decal 9m2',
    description: 'Thi công dán decal diện tích 9m2',
    category: 'construction',
    contact: 'Ngọc Tú 0395347015',
    workplace: 'SEMV',
    manpower: 'Tuấn Nam',
    assignedTo: 'tuannam',
    vehicle: 'Ford đen + xanh',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-04-13',
    createdAt: '2026-04-12',
  },
  {
    id: 'tc2',
    title: 'Dán decal 100m2 xám',
    description: 'Thi công dán decal 100m2 màu xám',
    category: 'construction',
    contact: 'Chang. 0983966310',
    workplace: 'SEVT',
    manpower: 'Tuấn Nam',
    assignedTo: 'tuannam',
    vehicle: 'Ford đen + xanh',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2026-04-13',
    createdAt: '2026-04-12',
  },
  {
    id: 'tc3',
    title: 'Dán decal 25m2',
    description: 'Dán decal diện tích 25m2',
    category: 'construction',
    contact: 'Đoàn 0977.740.123',
    workplace: 'SEVT',
    manpower: 'Chì Phương',
    assignedTo: 'chishuong',
    vehicle: 'Ford đen + xanh',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-04-13',
    createdAt: '2026-04-12',
  },
  // THIẾT KẾ
  {
    id: 'tk1',
    title: 'IMV-SDV(Vikor)',
    description: 'Thiết kế bản vẽ IMV-SDV',
    category: 'design',
    assignedTo: 'admin',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-04-13',
    createdAt: '2026-04-12',
  },
  {
    id: 'tk2',
    title: '2112250916 in ảnh',
    description: 'Xử lý file in ảnh 2112250916',
    category: 'design',
    assignedTo: 'admin',
    priority: 'low',
    status: 'todo',
    dueDate: '2026-04-13',
    createdAt: '2026-04-12',
  },
  // SẢN XUẤT
  {
    id: 'sx1',
    title: '100 biển mica 1mm 1 mặt',
    description: 'Gia công 100 biển mica độ dày 1mm',
    category: 'production',
    assignedTo: 'admin',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-04-13',
    createdAt: '2026-04-12',
  },
  {
    id: 'sx2',
    title: '20m2 in ảnh',
    description: 'Sản xuất in ảnh diện tích 20m2',
    category: 'production',
    assignedTo: 'admin',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-04-13',
    createdAt: '2026-04-12',
  },
];
